site_name: Server Seafile Manual


pages:

- Summary: index.md
# Summary

- 'Introduction': README.md
- 'Overview': overview/README.md
- 'Deploying Seafile under Linux': deploy/README.md
- 'Deploy Seafile under Windows': deploy_windows/deploy_with_windows.md
- 'Deploy Seafile Pro Edition': deploy_pro/README.md
- 'Server Configuration and Customization': config/README.md
- 'Administration': maintain/README.md
- 'WebDAV and FUSE extensions': extension/README.md
- 'Security and Auditing': security/README.md
- 'Developing': develop/README.md

theme: readthedocs
