site_name: Server Seafile Manual


pages:

- Summary: index.md
# Summary

- 'Introduction': README.md
- 'Overview': overview/README.md
- 'Deploying Seafile under Linux':
   - deploy/README.md
   - 'Other Deployment Notes':
       - 'Start Seafile at System Bootup': deploy/start_seafile_at_system_bootup.md
       - 'Firewall settings': deploy/using_firewall.md
       - 'Logrotate': deploy/using_logrotate.md
       - 'Add Memcached': deploy/add_memcached.md
       - 'Deploy Seafile behind NAT': deploy/deploy_seafile_behind_nat.md
       - 'Deploy Seahub at Non-root domain': deploy/deploy_seahub_at_non-root_domain.md
       - 'Migrate From SQLite to MySQL': deploy/migrate_from_sqlite_to_mysql.md
   - 'Common Problems for Setting up Server': faq.md
   - 'New Directory Layout in Seafile Server 5.0.0': deploy/new_directory_layout_5_0_0.md
- 'Deploy Seafile under Windows': deploy_windows/deploy_with_windows.md
- 'Deploy Seafile Pro Edition':
   - deploy_pro/README.md
   - 'Virus Scan':
       - deploy_pro/virus_scan.md
       - 'Virus Scan With Kav4fs': deploy_pro/virus_scan_with_kav4fs.md
   - 'Web Resumable File Upload': deploy_pro/web_resumable_upload.md
   - 'Storage Backends':
       - 'Amazon S3 Backend': deploy_pro/setup_with_amazon_s3.md
       - 'Ceph Backend': deploy_pro/setup_with_ceph.md
       - 'OpenStack Swift Backend': deploy_pro/setup_with_swift.md
   - 'Cluster Deployment':
       - 'Deploy in a cluster': deploy_pro/deploy_in_a_cluster.md
       - 'Setup with MariaDB and Ceph': deploy_pro/clustering_with_mariadb_ceph.md
       - 'Setup Seafile cluster with NFS': deploy_pro/setup_seafile_cluster_with_nfs.md
       - 'Enable search and background tasks in a cluster': deploy_pro/enable_search_and_background_tasks_in_a_cluster.md
       - 'Upgrade a cluster': deploy_pro/upgrade_a_cluster.md
   - 'Real-time Backup Server': deploy_pro/real_time_backup.md
   - 'Configurable Options': deploy_pro/configurable_options.md
   - 'FAQ': deploy_pro/faq_for_seafile_pro_server.md
   - 'License': deploy_pro/seafile_professional_sdition_software_license_agreement.md
- 'Server Configuration and Customization': config/README.md
- 'Administration': maintain/README.md
- 'WebDAV and FUSE extensions': extension/README.md
- 'Security and Auditing': security/README.md
- 'Developing': develop/README.md

theme: readthedocs
