site_name: Server Seafile Manual


pages:

- Summary: index.md
# Summary

- '概览':
   - overview/README.md
   - 'Seafile 组件': overview/components.md
   - '常见问题解答': faq.md
   - '我要参与': contribution.md
- 'Linux 下部署 Seafile 服务器':
   - deploy/README.md
   - '部署 Seafile 服务器（使用 SQLite）': deploy/using_sqlite.md
   - '部署 Seafile 服务器（使用 MySQL）': deploy/using_mysql.md
   - 'Nginx 下配置 Seahub': deploy/deploy_with_nginx.md
   - 'Nginx 下启用 Https': deploy/https_with_nginx.md
   - 'Apache 下配置 Seahub': deploy/deploy_with_apache.md
   - 'Apache 下启用 Https': deploy/https_with_apache.md
   - '升级': deploy/upgrade.md
   - '其他部署说明':
       - '开机启动 Seafile': deploy/start_seafile_at_system_bootup.md
       - '防火墙设置': deploy/using_firewall.md
       - 'Logrotate 管理系统日志': deploy/using_logrotate.md
       - '使用 Memcached': deploy/add_memcached.md
       - '使用 NAT': deploy/deploy_seafile_behind_nat.md
       - '从 SQLite 迁移至 MySQL': deploy/migrate_from_sqlite_to_mysql.md
   - '安装常见问题': faq.md
   - 'Seafile 服务器 5.0 中配置文件新位置': deploy/new_directory_layout_5_0_0.md
- 'Windows 下部署 Seafile 服务器':
   - deploy_windows/deploy_with_windows.md
   - '下载安装 Windows 版 Seafile 服务器': deploy_windows/download_and_setup_seafile_windows_server.md
   - '安装 Seafile 为 Windows 服务': deploy_windows/install_seafile_server_as_a_windows_service.md
   - '所用端口说明': deploy_windows/ports_used_by_seafile_windows_server.md
   - '升级': deploy_windows/upgrading_seafile_windows_server.md
   - '从 Windows 迁移到 Linux': deploy_windows/migrate_from_win_to_linux.md
   - '垃圾回收': deploy_windows/windows_gc.md
- '部署 Seafile 专业版服务器':
   - deploy_pro/README.md
   - '下载安装 Seafile 专业版服务器': deploy_pro/download_and_setup_seafile_professional_server.md
   - '从社区版迁移至专业版': deploy_pro/migrate_from_seafile_community_server.md
   - '升级': deploy_pro/upgrading_seafile_professional_server.md
   - '专业版 AD/LDAP 配置': deploy_pro/using_ldap_pro.md
   - '同步 AD 群组': deploy_pro/ldap_group_sync.md
   - '开启 Office/PDF 文件在线预览': deploy_pro/office_documents_preview.md
   - 'Office Web App 集成': deploy_pro/office_web_app.md
   - '文件搜索说明': deploy_pro/details_about_file_search.md
   - '病毒扫描':
       - deploy_pro/virus_scan.md
       - '卡巴斯基病毒扫描配置': deploy_pro/virus_scan_with_kav4fs.md
   - 'Web 文件断点续传': deploy_pro/web_resumable_upload.md
   - '存储后端':
       - 'Amazon S3 下安装': deploy_pro/setup_with_amazon_s3.md
       - 'OpenStackSwift 下安装': deploy_pro/setup_with_openstackswift.md
       - 'Ceph 下安装': deploy_pro/setup_with_ceph.md
       - '使用阿里云OSS存储': deploy_pro/setup_with_oss.md
   - '集群部署':
       - '集群部署': deploy_pro/deploy_in_a_cluster.md
       - '集群中启用搜索和后台服务': deploy_pro/enable_search_and_background_tasks_in_a_cluster.md
       - 'NFS 下集群安装': deploy_pro/setup_seafile_cluster_with_nfs.md
       - '升级集群': deploy_pro/upgrade_a_cluster.md
   - '配置选项': deploy_pro/configurable_options.md
   - '常见问题解答': deploy_pro/faq_for_seafile_pro_server.md
   - '软件许可协议': deploy_pro/license-pro-edition.md
- '服务器个性化配置':
   - config/README.md
   - 'ccnet.conf': config/ccnet-conf.md
   - 'seafile.conf': config/seafile-conf.md
   - 'seahub_settings.py': config/seahub_settings_py.md
   - '发送邮件提醒': config/sending_email.md
   - '个性化邮件提醒': config/customize_email_notifications.md
   - '存储容量与文件上传/下载大小限制': config/quota_and_size_options.md
   - '自定义 Web': config/seahub_customization.md
- '日常维护':
   - maintain/README.md
   - '账户管理': maintain/account.md
   - '日志': maintain/logs.md
   - '备份与恢复': maintain/backup_recovery.md
   - 'Seafile FSCK': maintain/seafile_fsck.md
   - 'Seafile GC': maintain/seafile_gc.md
- 'WebDAV 和 FUSE 扩展':
   - extension/README.md
   - 'WebDAV 扩展': extension/webdav.md
   - 'FUSE 扩展': extension/fuse.md
- '安全选项':
   - security/README.md
   - '安全特性': security/security_features.md
   - '日志和审计': security/auditing.md
- '开发文档':
   - develop/README.md

theme: readthedocs
